import hashlib,json,re,sys
from pathlib import Path
ROOT=Path.cwd(); BASE=ROOT/'.caprmedio_caprmedio/_projection/core-entity-review/nodes'; sys.path.insert(0,str(BASE/'support'))
from snapshot_sources import read_source,source_pins
p=BASE/'inputs/slices/CA-P-1948.input.json'; x=json.loads(p.read_text()); pins=source_pins(); cat={}; rows=[]
def evidence(a):
 raw=read_source(a).decode(); ls=raw.splitlines(); st=[i for i,l in enumerate(ls) if re.match(r'^## (Claim|Definition|Operation|Procedure|Condition|Evaluation|Details)\b',l)] or [i for i,l in enumerate(ls) if l.startswith('## Scope')] or [i for i,l in enumerate(ls) if l.startswith('## ')]; i=st[0]; j=next((k for k in range(i+1,len(ls)) if ls[k].startswith('## ')),len(ls)); q='\n'.join(ls[i+1:j]); s=pins[a]; k=f'{a}-{i+2}'; cat[k]={'evidence_ref':k,'atom_id':a,'atom_revision':s['atom_revision'],'carrier_path':s['carrier_path'],'carrier_sha256':s['carrier_sha256'],'start_line':i+2,'end_line':j,'quote':q,'text_sha256':hashlib.sha256(q.encode()).hexdigest()}; return k
for n in x['nodes']:
 ids=n['governing_source_atom_ids'] or n['source_atom_ids']; a=ids[0]; ident=n['identity']; special={'Scope Unit/Local Order':'CA-D-442','Scope Unit/Carrier':'CA-D-505','Scope Unit Graph':'CA-R-1655','Scripted Migration':'CA-R-1554'}; a=special.get(ident,a); e=evidence(a); has=bool(n['governing_source_atom_ids']) or ident in special; disp='retain' if has else 'question'; conf=95 if has else 0; reason=(f'Captured Main Content explicitly establishes the qualified constraint/binding meaning of {ident}; no duplicate, redundancy, or safe generalization is evidenced.' if has else f'Captured occurrence source {a} was checked, but no target-specific defining source is supplied for {ident}.'); checks={z:{'finding':'captured-definition-checked' if has else 'defining-source-gap','reason':f'{z.replace("_"," ").title()} checked against captured target evidence for {ident}.','evidence_refs':[e]} for z in ('duplicates','redundancy','empty_definition','distinct_meaning','generalization')}; rows.append({'identity':ident,'disposition':disp,'confidence_percent':conf,'reason':reason,'checks':checks,'evidence_refs':[e],'checked_source_atom_ids':ids,'proposal':({'action':'retain','native_admission':'not_performed'} if has else None),'question':(None if has else f'Which captured source defines {ident} distinctly, including its relation to structural ownership, applicability, Carrier, or Run where relevant?')})
o={'source_task':x['source_task'],'batch':x['batch'],'baseline_inventory_sha256':x['baseline']['inventory_sha256'],'input_file_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'partition_sha256':x['partition_sha256'],'non_authoritative':True,'semantic_admission':'not_performed','source_migration':'not_performed','evidence_catalogue':cat,'nodes':rows}; (BASE/'slices/CA-P-1948.review.json').write_text(json.dumps(o,indent=2)+'\n')
