#!/usr/bin/env python3
"""Create-only CA-P-1908 captured-snapshot candidate presentation.

The default is a no-write dry run.  ``--persist`` creates absent artifacts or
accepts byte-identical ones; it never overwrites a mismatching file.
``--verify-output`` checks all generated bytes without writing.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[5]
PRESENTATION_DIR = REPO_ROOT / ".caprmedio_caprmedio/_projection/core-entity-review/presentation"
REVIEW_ROOT = REPO_ROOT / ".caprmedio_caprmedio/_projection/core-entity-review"

OUTPUTS = {
    "candidate.entities.indented.txt": PRESENTATION_DIR / "candidate.entities.indented.txt",
    "candidate.review.md": PRESENTATION_DIR / "candidate.review.md",
    "candidate.manifest.json": PRESENTATION_DIR / "candidate.manifest.json",
}

EXPECTED_INPUT_HASHES = {
    "node_marks": "1b9d751f95aa71486908b53b3d7f3f9825defae137be3d8792d45177587c48f8",
    "ledger": "f6efdcaddfbbb4d9f4607084ee77ca83c75de2566fd9506da51dac2493e02371",
    "structure": "04f2b8d3606ac30b74850ab9ff53ebebfcbcffd1cda1e5ad2d948662c085e34b",
    "design": "10733c9f1b6b8d5946acdc469e7cfe3ee710ed515f1de77eed765c2252652b9e",
    "rmed": "d7fd113a408c3bb70e17ab55cc86fd6746c3d5c74ff27a9a864632ec6de999aa",
    "snapshot": "bfd6a7d93745d69432111df37ca139ba727a1ad06e821d94d3c059e44169ee23",
    "operator": "53eeb7a3fdaa002cd05170fe185cfb5baeea72814a1f32567d8eea6f56ac65cb",
    "scope": "d4ea636d540b0558c1a0fbb8263760947e1f0768840c43b3ed1d05c96b497453",
    "acceptance": "c2576865efcd2cfcc10a7075ad546b1c2d288cdae9f285eeaeb61f858bbf2e9b",
}


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def read_json(relative: str) -> tuple[dict[str, Any], dict[str, Any]]:
    path = REPO_ROOT / relative
    raw = path.read_bytes()
    return json.loads(raw), {"path": relative, "bytes": len(raw), "sha256": sha256_bytes(raw)}


def path_parts(display_path: str) -> list[str]:
    """Return operator-visible segments: ``A.B/C: D`` -> A, .B, /C, : D."""
    parts = re.split(r"([/.:@])", display_path)
    if not parts or not parts[0]:
        raise ValueError(f"invalid empty display path: {display_path!r}")
    result = [parts[0]]
    for index in range(1, len(parts), 2):
        if index + 1 >= len(parts) or not parts[index + 1]:
            raise ValueError(f"invalid terminal display operator: {display_path!r}")
        result.append(parts[index] + parts[index + 1])
    return result


def mark_label(identity: str, disposition: str, unresolved_drop: set[str]) -> str:
    if identity in unresolved_drop:
        return "QUESTION; DROP CANDIDATE unresolved"
    labels = {
        "retain": "RETAIN",
        "question": "QUESTION",
        "consolidate": "CONSOLIDATE CANDIDATE",
        "generalize": "GENERALIZE CANDIDATE",
    }
    try:
        return labels[disposition]
    except KeyError as error:
        raise ValueError(f"unsupported disposition for {identity}: {disposition}") from error


def make_tree(rows: list[dict[str, Any]]) -> dict[str, Any]:
    root: dict[str, Any] = {"children": {}, "identity": None, "mark": None}
    for row in sorted(rows, key=lambda item: (item["display_path"], item["identity"])):
        node = root
        for label in path_parts(row["display_path"]):
            node = node["children"].setdefault(label, {"children": {}, "identity": None, "mark": None})
        if node["identity"] is not None:
            raise ValueError(f"duplicate display leaf: {row['display_path']!r}")
        node["identity"] = row["identity"]
        node["mark"] = row["mark"]
    return root


def render_tree(tree: dict[str, Any], indent: int = 0) -> list[str]:
    lines: list[str] = []
    for label in sorted(tree["children"], key=str.casefold):
        node = tree["children"][label]
        suffix = (
            f" [original identity: {node['identity']}; {node['mark']}]"
            if node["identity"] is not None
            else " (prefix support only)"
        )
        lines.append(" " * indent + label + suffix)
        lines.extend(render_tree(node, indent + 2))
    return lines


def compact_ref(pointer: dict[str, Any]) -> str:
    key = pointer["source_ref_key"]
    return key.split(":", 1)[0]


def review_row_summary(row: dict[str, Any]) -> str:
    proposal = row["review_row"].get("proposal")
    if not proposal:
        return "No semantic replacement is proposed."
    if isinstance(proposal, str):
        return proposal
    target = next((proposal[key] for key in ("candidate_display_parent", "candidate_display_family", "candidate_display_name") if proposal.get(key)), None)
    basis = proposal.get("candidate_basis")
    risk = proposal.get("lost_distinctions_risk")
    parts = []
    if target:
        parts.append(f"display target: `{target}`")
    if basis:
        parts.append(str(basis))
    if risk:
        parts.append(f"risk retained: {risk}")
    return "; ".join(parts) if parts else "Structured proposal retained in nodes.dispositions.json."


def markdown_link(relative: str, label: str) -> str:
    return f"[{label}]({relative})"


def render(inputs: dict[str, tuple[dict[str, Any], dict[str, Any]]]) -> dict[str, bytes]:
    node_marks, node_marks_pin = inputs["node_marks"]
    ledger, ledger_pin = inputs["ledger"]
    structure, structure_pin = inputs["structure"]
    design, design_pin = inputs["design"]
    rmed, rmed_pin = inputs["rmed"]
    snapshot_context, snapshot_pin = inputs["snapshot"]
    operator_direction, operator_pin = inputs["operator"]
    scope_decision, scope_pin = inputs["scope"]
    acceptance, acceptance_pin = inputs["acceptance"]

    if node_marks["source_context"]["git_commit"] != "a971d0e00c33c779f485fc8cad63194894d440fb":
        raise ValueError("presentation is restricted to the selected captured Core snapshot")
    if node_marks["source_context"]["current_core_claimed"] is not False:
        raise ValueError("presentation must not make a current-Core claim")
    for key, expected_hash in EXPECTED_INPUT_HASHES.items():
        pin = inputs[key][1]
        if pin["sha256"] != expected_hash:
            raise ValueError(f"unexpected frozen input: {key}")

    marks = node_marks["node_disposition_marks"]
    crosswalk = structure["node_identity_crosswalk"]
    if len(marks) != 706 or len(crosswalk) != 706:
        raise ValueError("expected exactly 706 marked identities and crosswalk rows")
    marks_by_id = {row["identity"]: row for row in marks}
    crosswalk_by_id = {row["preserved_identity"]: row for row in crosswalk}
    if set(marks_by_id) != set(crosswalk_by_id):
        raise ValueError("mark/crosswalk identity mismatch")

    groups = {entry["display_group"]: {member["qualified_identity"] for member in entry["members"]}
              for entry in structure["display_groups"]}
    anchors = set(structure["non_temporal_broad_model_anchors"]["qualified_identities"])
    continuant = groups["Continuant"]
    occurrent = groups["Occurrent"]
    all_ids = set(marks_by_id)
    unclassified = all_ids - continuant - occurrent - anchors
    if len(continuant) != 17 or len(occurrent) != 3 or len(anchors) != 4 or len(unclassified) != 682:
        raise ValueError("unexpected candidate display-bucket coverage")
    if (continuant & occurrent) or (continuant & anchors) or (occurrent & anchors):
        raise ValueError("candidate display buckets overlap")

    unresolved_drop = {item["identity"] for item in node_marks["unresolved_drop_annotations"]}
    def rows_for(identities: set[str]) -> list[dict[str, Any]]:
        result = []
        for identity in identities:
            crosswalk_row = crosswalk_by_id[identity]
            mark = mark_label(identity, marks_by_id[identity]["review_row"]["disposition"], unresolved_drop)
            if crosswalk_row["display_rebase"] == "blocked_chain_original_preserved":
                mark += "; LEGACY RELATION UNRESOLVED"
            result.append({"identity": identity, "display_path": crosswalk_row["proposed_display_path"], "mark": mark})
        return result

    inventory_sections = [
        ("Continuant (display-only; 17 identities)", continuant),
        ("Occurrent (display-only; 3 identities)", occurrent),
        ("Broad model anchors (not temporally classified; 4 identities)", anchors),
        ("Explicitly unclassified (682 identities; no default parentage inferred)", unclassified),
    ]
    actual_identity_count = 0
    top_level_labels = 0
    inventory_lines = [
        "CA-P-1908 candidate Entities Graph — captured snapshot only",
        "Two-space indentation and prefix nodes are presentation only: no native Entity relation, Subject rewrite, or ontology adoption follows.",
        "Operators apply only to separately evidenced display decisions: / broader-to-narrower; . bearer qualification; : allowed value; @ carrier binding only when separately evidenced.",
        "A preserved legacy path marked LEGACY RELATION UNRESOLVED does not acquire that relation. A RETAIN identity does not approve any relation. All original identities remain annotations.",
        "",
        "Primary inventory — every original identity appears exactly once",
    ]
    for title, identities in inventory_sections:
        tree = make_tree(rows_for(identities))
        top_level_labels += len(tree["children"])
        inventory_lines.append("  " + title)
        rendered = render_tree(tree, indent=4)
        actual_identity_count += sum("[original identity:" in line for line in rendered)
        inventory_lines.extend(rendered)
    if actual_identity_count != 706:
        raise ValueError(f"primary inventory rendered {actual_identity_count}, expected 706")

    inventory_lines.extend([
        "",
        "Candidate-only display supplements",
        "  Seven conditional inherited constraints, ten Term-taxonomy proposals, five reduction proposals, 123 blocked legacy relation chains, and the exact 117 questions remain in the pinned ledgers; none is admitted by this rendering.",
        "  Two unresolved DROP CANDIDATE marks are visible above as QUESTION and remain preserved identities.",
        "  RMED pointer views are separately rendered in ../design/rmed.roles.indented.txt and ../design/rmed.entities.indented.txt; their GOVERNS and DEPENDS_ON channels remain distinct.",
        "  M/E/D links are pointer-derived associations, not proven applicability. No empty M/E/D slot is invented.",
    ])
    candidate_text = ("\n".join(inventory_lines) + "\n").encode("utf-8")

    non_retain = [row for row in marks if row["review_row"]["disposition"] in {"consolidate", "generalize"}]
    if len(non_retain) != 5:
        raise ValueError("expected exactly five reduction proposals")
    distribution = Counter(row["review_row"]["disposition"] for row in marks)
    questions = [row for row in marks if row["review_row"]["disposition"] == "question"]
    if len(questions) != 117:
        raise ValueError("expected 117 retained questions")

    role_lines = []
    governing_total = dependency_total = 0
    for role in rmed["role_centered_overview"]["role_trees"]:
        governing_total += role["governing_claim_pointer_count"]
        dependency_total += role["dependency_pointer_count"]
        role_lines.append(
            f"- **{role['rmed_role']}** — {role['role_meaning']}: "
            f"{role['governing_claim_pointer_count']} GOVERNS pointers to {role['governed_identity_count']} identities; "
            f"{role['dependency_pointer_count']} DEPENDS_ON pointers to {role['dependency_identity_count']} identities."
        )
    if (governing_total, dependency_total) != (805, 2844):
        raise ValueError("unexpected RMED pointer totals")

    reductions = "\n".join(
        f"- `{row['identity']}` — **{mark_label(row['identity'], row['review_row']['disposition'], unresolved_drop)}** "
        f"({row['review_row']['confidence_percent']}%): {review_row_summary(row)}"
        for row in sorted(non_retain, key=lambda item: item["identity"].casefold())
    )
    constraints = "\n".join(
        f"- `{constraint['constraint_id']}` — applies when: {constraint['applies_when']} Rule: {constraint['rule']}"
        for constraint in design["inherited_constraints"]
    )
    terms = "\n".join(
        f"- `{relation['qualified_parent']}` / `{relation['qualified_child']}` — `/` display; canonical "
        f"`{relation['canonical_relation']}` `{relation['qualified_child']} → {relation['qualified_parent']}` "
        f"(narrower→broader; {relation['graph_kind']} candidate; {relation['native_admission']})."
        for relation in design["additional_relations"]
    )
    review_text = f"""# CA-P-1908 candidate Entities Graph review

This is a **CANDIDATE** derived from the Operator-selected captured Core snapshot `{node_marks['source_context']['git_commit']}`. It is not current-Core evidence, native admission, Operator acceptance, a Subject migration, a source change, or a completed Run. The next action is the CA-P-1909 Operator approval gate.

## Read first

- {markdown_link('candidate.entities.indented.txt', 'Primary 706-identity candidate inventory')} is a two-space display tree. Every original identity appears once as an annotation; prefix labels support display only.
- The preserved, source-pinned details remain in {markdown_link('../nodes/nodes.dispositions.json', 'node-disposition ledger')} and {markdown_link('../nodes/relations.marked.ledger.json', 'occurrence-to-proposed-relation ledger')}. Those files retain all reasons, five checks, source evidence, questions, effects, and non-native boundaries.
- The two pointer views remain shared rather than copied: {markdown_link('../design/rmed.roles.indented.txt', 'R/M/E/D role-centred tree')}, {markdown_link('../design/rmed.entities.indented.txt', 'Entity-centred pointer tree')}, and {markdown_link('../design/rmed.views.json', 'machine-readable RMED view')}. GOVERNS and DEPENDS_ON are separate; M/E/D associations are not proven applicability.

## Before and candidate accounting

| Measure | Value |
| --- | ---: |
| Original identities retained in primary inventory | 706 |
| Before literal syntactic roots | 346 |
| Before standalone roots | 293 |
| Continuant display members | 17 |
| Occurrent display members | 3 |
| Broad non-temporal model anchors | 4 |
| Explicitly unclassified identities | 682 |
| Rendered top-level display labels | {top_level_labels} |
| Retain marks | {distribution['retain']} |
| Consolidate candidates | {distribution['consolidate']} |
| Generalize candidates | {distribution['generalize']} |
| Questions retained | {distribution['question']} |
| Unresolved drop annotations | {len(unresolved_drop)} |

The rendered-label count is a display calculation from the explicit crosswalk, not a candidate literal-root count or a claim of independent ontology roots. Continuant and Occurrent are local display lenses, not BFO adoption or taxonomy admission.

## Compact notation and boundaries

`/` presents broader-to-narrower only where a separately evidenced display decision says so (canonical direction would be narrower-to-broader); `.` presents bearer qualification; `:` presents an allowed value; `@` is a carrier binding only where separately evidenced. A `LEGACY RELATION UNRESOLVED` path preserves old syntax without classifying it. Display formatting does not serialize Subjects or admit a relation; a retained node does not approve a relation. Entity and Term graph ownership stay distinct: the ten `/` proposals below are Term-graph candidates only.

## Candidate marks requiring an Operator decision

{reductions}

The two **DROP CANDIDATE unresolved** annotations remain questions for `Applicable Methodology Revision` and `Projection/Revision`; neither identity is deleted. All {len(questions)} questions retain a null semantic proposal and their specific question in the node-disposition ledger.

## Conditional inherited constraints — display only

{constraints}

These are conditional shared rules, not concrete Carrier inheritance, actual bindings, default Settings copies, or universal IS_BORNE_BY facts.

## Ten separately evidenced Term-taxonomy proposals

{terms}

## Parallel RMED and Entity-centred pointer views

{chr(10).join(role_lines)}

Across the shared view there are {governing_total} GOVERNS and {dependency_total} DEPENDS_ON pointers. Sources remain shared Claim/provenance records, not duplicate Entity nodes. R supplies model skeleton/required results, M construction conventions, E checks, and D Carrier/formats/placement; Operations and Concern remain outside RMED construction guidance.

## Content presentation direction

Candidate Atom body: `Substance`, `Substance Scope`, and optional `Details`. Role labels are `Claim` (RMED), `Objective` (Plan), `Question` (Analysis), `Issue` (Concern), and `Operation` (Operations). They are presentation labels, not new native kinds. An omitted Substance Scope means the full governed Subject **and** full owning Scope Unit only; otherwise Scope must remain explicit. It is applicability, not ownership. This Operator direction is separately pinned and is not retroactive Core evidence.

## Reproducibility and limits

Use {markdown_link('candidate.manifest.json', 'candidate.manifest.json')} with `support/render_candidate.py --verify-output`. The manifest pins the exact accepted review inputs, captured snapshot, Scope decision, source context, producer, outputs, canonical candidate JSON, and the CA-P-1907/CA-P-1938 receipt commit. It does not rebind to current Core or infer a new root/taxonomy/Carrier relation.

**Approval gate:** no source, Subject, Core, native graph, runtime, or history change is authorized until the Operator accepts a separately reviewed candidate and a later exact migration preview.
"""
    review_bytes = review_text.encode("utf-8")

    candidate_json_canonical_sha256 = sha256_bytes(canonical_json_bytes(structure))
    producer_path = ".caprmedio_caprmedio/_projection/core-entity-review/presentation/support/render_candidate.py"
    producer_bytes = (REPO_ROOT / producer_path).read_bytes()
    rmed_role_text = REVIEW_ROOT / "design/rmed.roles.indented.txt"
    rmed_entity_text = REVIEW_ROOT / "design/rmed.entities.indented.txt"
    rmed_text_pins = [
        {"path": path.relative_to(REPO_ROOT).as_posix(), "bytes": len(path.read_bytes()), "sha256": sha256_bytes(path.read_bytes())}
        for path in (rmed_role_text, rmed_entity_text)
    ]
    manifest = {
        "schema_version": 1,
        "source_task": "CA-P-1908",
        "presentation_status": "CANDIDATE",
        "non_authoritative": True,
        "operator_acceptance": "not_performed",
        "native_admission": "not_performed",
        "semantic_admission": "not_performed",
        "source_migration": "not_performed",
        "captured_source_context": {
            "kind": "captured_snapshot",
            "git_commit": node_marks["source_context"]["git_commit"],
            "current_core_claimed": False,
            "source_pins_checked": node_marks["source_context"]["source_pins_checked"],
            "captured_context": snapshot_pin,
            "ca_d_494": {"atom_id": "CA-D-494", "revision": 2, "note": "revision 3 is outside this captured review"},
        },
        "operator_directions": {
            "substance_content": operator_pin,
            "scope_omission": scope_pin,
            "rule": "Omit Substance Scope only for the full governed Subject AND full owning Scope Unit; otherwise show it explicitly.",
        },
        "input_pins": {
            "nodes_dispositions": node_marks_pin,
            "relations_marked_ledger": ledger_pin,
            "candidate_structure_marked": structure_pin,
            "structure_design": design_pin,
            "rmed_views": rmed_pin,
            "rmed_text_views": rmed_text_pins,
            "nodes_acceptance": acceptance_pin,
        },
        "candidate_json": {
            "path": "../nodes/candidate.structure.marked.json",
            "file_sha256": structure_pin["sha256"],
            "canonical_sorted_compact_json_sha256": candidate_json_canonical_sha256,
            "canonical_encoding": "UTF-8 JSON sort_keys=true separators=(',', ':') without newline",
        },
        "completion_receipts": {
            "receipt_commit": "94776a14a368827a758534eb9c5c0109d649f309",
            "ca_p_1907": {"atom_id": "CA-P-1907", "status": "Done", "plan_version": 14, "plan_carrier_sha256": "9ac74a857d8356db6e4a0f68890ca8e19babb6b3644a5f831fb681515046eedf", "locator_basis": "receipt commit, not a mutable current path"},
            "ca_p_1938": {"atom_id": "CA-P-1938", "status": "Done", "plan_version": 3, "plan_carrier_sha256": "b2bb487194a14212560e109a4c763d4f107611f033c7c7151335c534d50fa022", "acceptance_record_sha256": acceptance_pin["sha256"], "independent_verifier_sha256": "c56e4067c101a2c49375bfb952e783b5d9cf50da47f062a5321601f910416f41"},
        },
        "counts": {
            "original_identity_count": 706,
            "primary_inventory_identity_count": actual_identity_count,
            "continuant": len(continuant),
            "occurrent": len(occurrent),
            "broad_non_temporal_anchors": len(anchors),
            "unclassified": len(unclassified),
            "before_literal_syntactic_roots": structure["root_counts"]["before"]["literal_syntactic_roots"],
            "before_standalone_roots": structure["root_counts"]["before"]["standalone_roots"],
            "rendered_top_level_display_labels": top_level_labels,
            "dispositions": dict(sorted(distribution.items())),
            "unresolved_drop_annotations": len(unresolved_drop),
            "inherited_constraints": len(design["inherited_constraints"]),
            "term_taxonomy_proposals": len(design["additional_relations"]),
            "rmed_governs_pointers": governing_total,
            "rmed_depends_on_pointers": dependency_total,
        },
        "view_boundaries": {
            "presentation_nesting_is_not_native_relation": True,
            "governs_and_depends_on_separate": True,
            "med_pointers_not_proven_applicability": True,
            "no_empty_med_slot_invented": True,
            "carrier_binding_display_only_when_evidenced": True,
        },
        "producer": {"path": producer_path, "sha256": sha256_bytes(producer_bytes)},
        "rendered_outputs": {
            "candidate_entities_indented": {"path": "candidate.entities.indented.txt", "bytes": len(candidate_text), "sha256": sha256_bytes(candidate_text)},
            "candidate_review": {"path": "candidate.review.md", "bytes": len(review_bytes), "sha256": sha256_bytes(review_bytes)},
        },
        "reproduction": {
            "dry_run": "UV_CACHE_DIR=.caprmedio_tmp/cache/uv uv run --offline --no-project --no-env-file --python 3.14 python -B .caprmedio_caprmedio/_projection/core-entity-review/presentation/support/render_candidate.py",
            "verify_output": "UV_CACHE_DIR=.caprmedio_tmp/cache/uv uv run --offline --no-project --no-env-file --python 3.14 python -B .caprmedio_caprmedio/_projection/core-entity-review/presentation/support/render_candidate.py --verify-output",
            "persistence": "--persist creates only missing files and rejects any byte mismatch",
        },
    }
    manifest_bytes = json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False).encode("utf-8") + b"\n"
    return {**{OUTPUTS["candidate.entities.indented.txt"].name: candidate_text, OUTPUTS["candidate.review.md"].name: review_bytes}, OUTPUTS["candidate.manifest.json"].name: manifest_bytes}


def read_text_as_json_pin(relative: str) -> tuple[dict[str, Any], dict[str, Any]]:
    """Pin text inputs while retaining a minimal mapping for the renderer."""
    path = REPO_ROOT / relative
    raw = path.read_bytes()
    return {}, {"path": relative, "bytes": len(raw), "sha256": sha256_bytes(raw)}


def expected_outputs() -> dict[str, bytes]:
    """Render from JSON sources and text-only source pins."""
    inputs = {
        "node_marks": read_json(".caprmedio_caprmedio/_projection/core-entity-review/nodes/nodes.dispositions.json"),
        "ledger": read_json(".caprmedio_caprmedio/_projection/core-entity-review/nodes/relations.marked.ledger.json"),
        "structure": read_json(".caprmedio_caprmedio/_projection/core-entity-review/nodes/candidate.structure.marked.json"),
        "design": read_json(".caprmedio_caprmedio/_projection/core-entity-review/design/structure.design.json"),
        "rmed": read_json(".caprmedio_caprmedio/_projection/core-entity-review/design/rmed.views.json"),
        "snapshot": read_text_as_json_pin(".caprmedio_caprmedio/_projection/core-entity-review/nodes/snapshot.context.md"),
        "operator": read_text_as_json_pin(".caprmedio_caprmedio/_projection/core-entity-review/design/operator.decisions.md"),
        "scope": read_text_as_json_pin(".caprmedio_caprmedio/_projection/core-entity-review/nodes/scope.omission.decision.md"),
        "acceptance": read_text_as_json_pin(".caprmedio_caprmedio/_projection/core-entity-review/nodes/nodes.acceptance.md"),
    }
    return render(inputs)


def assert_safe_output_directory() -> None:
    """Reject symlinked/non-directory routing before any output is created."""
    directory = PRESENTATION_DIR
    while True:
        if directory.is_symlink() or not directory.is_dir():
            raise SystemExit(f"unsafe output directory: {directory}")
        if directory == REPO_ROOT:
            break
        if REPO_ROOT not in directory.parents:
            raise SystemExit(f"output directory escapes repository: {directory}")
        directory = directory.parent


def persist_outputs(expected: dict[str, bytes]) -> None:
    """Preflight every path, then exclusively create only genuinely absent files."""
    assert_safe_output_directory()
    missing: list[tuple[Path, bytes]] = []
    for name, content in expected.items():
        path = PRESENTATION_DIR / name
        if path.parent != PRESENTATION_DIR or path.is_symlink():
            raise SystemExit(f"unsafe output path: {path}")
        if path.exists():
            if not path.is_file():
                raise SystemExit(f"non-file output path: {path}")
            if path.read_bytes() != content:
                raise SystemExit(f"refusing to overwrite mismatching output: {path}")
        else:
            missing.append((path, content))

    created: list[tuple[Path, bytes]] = []
    try:
        for path, content in missing:
            # x mode provides exclusive creation if another writer races after preflight.
            with path.open("xb") as output:
                output.write(content)
                output.flush()
                os.fsync(output.fileno())
            created.append((path, content))
    except Exception:
        # Remove only files this invocation exclusively created and whose bytes still match.
        for path, content in reversed(created):
            if path.exists() and not path.is_symlink() and path.is_file() and path.read_bytes() == content:
                path.unlink()
        raise


def verify_outputs(expected: dict[str, bytes]) -> None:
    assert_safe_output_directory()
    failures = []
    for name, content in expected.items():
        path = PRESENTATION_DIR / name
        if path.is_symlink() or not path.is_file() or path.read_bytes() != content:
            failures.append(name)
    if failures:
        raise SystemExit("verification failed: " + ", ".join(failures))


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--persist", action="store_true", help="create absent byte-exact outputs")
    mode.add_argument("--verify-output", action="store_true", help="verify existing output bytes")
    args = parser.parse_args()
    expected = expected_outputs()
    if args.verify_output:
        verify_outputs(expected)
        print("verified", *(f"{name}:{sha256_bytes(content)}" for name, content in sorted(expected.items())))
        return 0
    if args.persist:
        persist_outputs(expected)
        print("persisted", *(f"{name}:{sha256_bytes(content)}" for name, content in sorted(expected.items())))
        return 0
    print("dry-run", *(f"{name}:{sha256_bytes(content)}" for name, content in sorted(expected.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
